import { FormEvent, useCallback, useEffect, useState } from "react";

type Tab = "overview" | "chat" | "models" | "tools" | "policies" | "agents" | "users" | "audit";
type Base = { id:number; name:string; displayName:string; description?:string; status:string; enabled:boolean };
type Health = { status:string; service:string; platform:string };
type Provider = { id:string; name:string; experimental:boolean; fields:string[] };
type Model = Base & { provider:string; modelId:string; configName:string };
type Tool = Omit<Base,"displayName"> & { className:string; methodName:string; description:string; requiresApproval:boolean; schema:string; auditPolicies:string[] };
type Policy = Base & { className:string; type:"authorization"|"audit"|"discovery" };
type Agent = Base & { modelName:string; systemPrompt:string; temperature:number; maxIterations:number; tools:string[]; policies:string[] };
type AuditEvent = { id:number; agentName:string; toolName:string; policyName:string; arguments:string; resultPreview:string; success:boolean; durationMs:number; error:string; createdAt:string };
type Identity = { username:string; authorized:boolean };
type JWTSession = { access_token:string; refresh_token:string; sub:string; iat:number; exp:number };
type AIUser = { id:number; username:string; enabled:boolean; createdAt:string; createdBy:string; agents:string[] };
type ChatMessage = { id?:number; role:"user"|"assistant"; content:string; createdAt?:string };
type ChatResponse = { conversationId:string; agentName:string; username:string; content:string; messages:ChatMessage[] };
type Data = { health:Health|null; identity:Identity|null; providers:Provider[]; models:Model[]; tools:Tool[]; policies:Policy[]; agents:Agent[]; availableAgents:Agent[]; users:AIUser[]; audits:AuditEvent[] };

const empty:Data={health:null,identity:null,providers:[],models:[],tools:[],policies:[],agents:[],availableAgents:[],users:[],audits:[]};
const labels:Record<string,string>={draft:"Borrador",approved:"Aprobado",suspended:"Suspendido",retired:"Retirado",authorization:"Autorizacion",audit:"Auditoria",discovery:"Descubrimiento"};
const titles:Record<Tab,string>={overview:"Gobernanza de IA",chat:"Chat de agentes",models:"Catalogo de modelos",tools:"Tools de AI Hub",policies:"Policies",agents:"Agentes",users:"Usuarios IA",audit:"Auditoria"};
const jwtStorageKey="irisJWT";
const readJWT=():JWTSession|null=>{try{return JSON.parse(sessionStorage.getItem(jwtStorageKey)||"null") as JWTSession|null}catch{return null}};
const saveJWT=(tokens:JWTSession)=>sessionStorage.setItem(jwtStorageKey,JSON.stringify(tokens));
let refreshInFlight:Promise<JWTSession>|null=null;
async function tokenRequest(path:"/login"|"/refresh",body:object):Promise<JWTSession>{const response=await fetch(`/api/app${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json().catch(()=>({})) as Partial<JWTSession>&{error?:string};if(!response.ok||!result.access_token)throw new Error(result.error??"No se pudo obtener el token de IRIS");return result as JWTSession}
async function refreshJWT():Promise<JWTSession>{const current=readJWT();if(!current?.refresh_token)throw new Error("La sesion JWT ha caducado");if(!refreshInFlight)refreshInFlight=tokenRequest("/refresh",{refresh_token:current.refresh_token,grant_type:"refresh_token"}).then(tokens=>{if(!tokens.sub)tokens.sub=current.sub;saveJWT(tokens);return tokens}).finally(()=>{refreshInFlight=null});return refreshInFlight}
async function api<T>(path:string,options?:RequestInit,retried=false):Promise<T>{const tokens=readJWT();if(!tokens)throw new Error("No hay una sesion JWT activa");const response=await fetch(`/api/app${path}`,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${tokens.access_token}`,...options?.headers}});if(response.status===401&&!retried){await refreshJWT();return api<T>(path,options,true)}let body:unknown={};try{body=await response.json()}catch{body={}}if(!response.ok)throw new Error((body as {error?:string}).error??`HTTP ${response.status}`);return body as T;}

export function App(){
 const [tab,setTab]=useState<Tab>("overview"),[data,setData]=useState<Data>(empty),[error,setError]=useState(""),[authenticated,setAuthenticated]=useState(()=>Boolean(readJWT()));
 const reload=useCallback(async()=>{try{setError("");const [health,providers,models,tools,policies,agents,availableAgents,users,audits]=await Promise.all([api<Health>("/health"),api<Provider[]>("/providers"),api<Model[]>("/models"),api<Tool[]>("/tools"),api<Policy[]>("/policies"),api<Agent[]>("/agents"),api<Agent[]>("/my-agents"),api<AIUser[]>("/ai-users"),api<AuditEvent[]>("/audit-events")]);const username=readJWT()?.sub??"";setData({health,identity:{username,authorized:availableAgents.length>0},providers,models,tools,policies,agents,availableAgents,users,audits});}catch(e){setError(e instanceof Error?e.message:"No se pudo cargar la plataforma");}},[]);
 useEffect(()=>{if(authenticated)void reload();},[authenticated,reload]);
 if(!authenticated)return <LoginView authenticated={()=>setAuthenticated(true)}/>;
 async function logout(){const tokens=readJWT();try{if(tokens)await fetch("/api/app/logout",{method:"POST",headers:{Authorization:`Bearer ${tokens.access_token}`}})}finally{sessionStorage.removeItem(jwtStorageKey);setData(empty);setAuthenticated(false)}}
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">AI</span><div><strong>Governance Hub</strong><small>InterSystems AI Hub</small></div></div><nav>{(["overview","chat","models","tools","policies","agents","users","audit"] as Tab[]).map((item,index)=><button key={item} className={tab===item?"nav-item active":"nav-item"} onClick={()=>setTab(item)}><span>{(index+1).toString().padStart(2,"0")}</span>{titles[item]}</button>)}</nav><div className="sidebar-foot"><span className={`pulse ${data.health?"online":""}`}/><div><strong>{data.identity?.username||"AI Hub"}</strong><small>{data.identity?.authorized?"Usuario autorizado":data.health?"Sin acceso a agentes":"Conectando..."}</small></div></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">CONTROL PLANE</p><h1>{titles[tab]}</h1></div><div className="environment"><span>Usuario IRIS</span><strong>{data.identity?.username||"-"}</strong><button className="secondary" onClick={logout}>Salir</button></div></header>{error&&<div className="alert">{error}<button onClick={()=>void reload()}>Reintentar</button></div>}<View tab={tab} data={data} reload={reload}/></main></div>;
}

function LoginView({authenticated}:{authenticated:()=>void}){const [error,setError]=useState(""),[loading,setLoading]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget),user=String(form.get("username")||""),password=String(form.get("password")||"");try{const tokens=await tokenRequest("/login",{user,password});saveJWT(tokens);authenticated()}catch(reason){sessionStorage.removeItem(jwtStorageKey);setError(reason instanceof Error?reason.message:"No se pudo iniciar sesion");setLoading(false)}}return <main className="login-shell"><section className="panel login-card"><span className="brand-mark">AI</span><p className="eyebrow">INTERSYSTEMS IRIS JWT</p><h1>Governance Hub</h1><p>IRIS emitirá un JWT firmado. Las policies decidirán qué agentes puede utilizar el sujeto autenticado.</p><form onSubmit={submit}><label className="field"><span>Usuario IRIS</span><input name="username" autoComplete="username" required/></label><label className="field"><span>Contraseña</span><input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={loading}>{loading?"Solicitando JWT...":"Entrar"}</button></form></section></main>}

function View({tab,data,reload}:{tab:Tab;data:Data;reload:()=>Promise<void>}){
 if(tab==="overview")return <Overview data={data}/>;
 if(tab==="chat")return <ChatView data={data}/>;
 if(tab==="users")return <UsersView users={data.users} agents={data.agents} reload={reload}/>;
 if(tab==="audit")return <AuditView events={data.audits}/>;
 if(tab==="models")return <ResourceView kind="model" items={data.models} data={data} reload={reload}/>;
 if(tab==="tools")return <ResourceView kind="tool" items={data.tools} data={data} reload={reload}/>;
 if(tab==="policies")return <ResourceView kind="policy" items={data.policies} data={data} reload={reload}/>;
 return <ResourceView kind="agent" items={data.agents} data={data} reload={reload}/>;
}
function Overview({data}:{data:Data}){const approved=(items:{status:string;enabled:boolean}[])=>items.filter(i=>i.status==="approved"&&i.enabled).length;return <><section className="hero-panel"><div><p className="eyebrow">PLATAFORMA DE AGENTES</p><h2>Controla que modelos razonan y que herramientas pueden ejecutar.</h2><p>Los metodos ObjectScript publicados por clases <code>%AI.Tool</code> se descubren directamente desde AI Hub. Cada agente recibe solo los metodos asignados y sus policies.</p></div><div className="hub-state"><span className="hub-icon ready">AI</span><strong>AI Hub activo</strong><small>Gobierno nativo dentro de IRIS</small></div></section><section className="metrics four"><Metric value={approved(data.models)} label="Modelos activos"/><Metric value={approved(data.tools)} label="Tools publicables"/><Metric value={approved(data.policies)} label="Policies activas"/><Metric value={approved(data.agents)} label="Agentes activos"/></section><section className="panel architecture"><div className="section-title"><p className="eyebrow">FLUJO GOBERNADO</p><h3>Del metodo al agente</h3></div><div className="flow"><Flow n="01" title="Definir" text="Clase %AI.Tool"/><b>-</b><Flow n="02" title="Descubrir" text="Catalogo del namespace"/><b>-</b><Flow n="03" title="Asignar" text="Tool y policies"/><b>-</b><Flow n="04" title="Ejecutar" text="%AI.Agent"/></div></section></>}
function Metric({value,label}:{value:number;label:string}){return <article className="metric"><strong>{value.toString().padStart(2,"0")}</strong><span>{label}</span><small>aprobados y habilitados</small></article>}
function Flow({n,title,text}:{n:string;title:string;text:string}){return <div className="flow-step"><small>{n}</small><strong>{title}</strong><span>{text}</span></div>}
function AuditView({events}:{events:AuditEvent[]}){return <section className="panel table-panel"><table><thead><tr><th>Fecha</th><th>Agente</th><th>Tool</th><th>Policy</th><th>Duracion</th><th>Resultado</th></tr></thead><tbody>{events.length?events.map(event=><tr key={event.id}><td>{event.createdAt}</td><td><code>{event.agentName}</code></td><td><code>{event.toolName}</code></td><td><code>{event.policyName}</code></td><td>{event.durationMs} ms</td><td><span className={`status status-${event.success?"approved":"suspended"}`}><i/>{event.success?"Correcto":"Error"}</span><small>{event.error||event.resultPreview}</small></td></tr>):<tr><td colSpan={6} className="empty">Todavia no hay ejecuciones auditadas.</td></tr>}</tbody></table></section>}

function ChatView({data}:{data:Data}){
 const available=data.availableAgents.filter(ok),[agentName,setAgentName]=useState(""),[conversationId,setConversationId]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]),[sending,setSending]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!agentName&&available.length)setAgentName(available[0].name)},[agentName,available]);
 function changeAgent(value:string){setAgentName(value);setConversationId("");setMessages([]);setError("")}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,field=form.elements.namedItem("message") as HTMLTextAreaElement,message=field.value.trim();if(!message||!agentName)return;setSending(true);setError("");setMessages(previous=>[...previous,{role:"user",content:message}]);field.value="";try{const response=await api<ChatResponse>("/chat",{method:"POST",body:JSON.stringify({agentName,message,conversationId})});setConversationId(response.conversationId);setMessages(response.messages)}catch(reason){setMessages(previous=>previous.slice(0,-1));setError(reason instanceof Error?reason.message:"No se pudo completar el chat")}finally{setSending(false)}}
 return <section className="chat-layout"><aside className="panel chat-config"><p className="eyebrow">CONTEXTO DE EJECUCION</p><label className="field"><span>Agente</span><select value={agentName} onChange={e=>changeAgent(e.target.value)}><option value="">Selecciona...</option>{available.map(agent=><option key={agent.id} value={agent.name}>{agent.displayName}</option>)}</select></label><div className="chat-identity"><span>Usuario IRIS</span><strong>{data.identity?.username||"-"}</strong><small className={data.identity?.authorized?"allowed":"denied"}>{data.identity?.authorized?"Autorizado para usar IA":"No autorizado"}</small></div>{conversationId&&<div className="chat-session"><span>Conversacion</span><code>{conversationId}</code></div>}<button className="secondary" onClick={()=>changeAgent(agentName)} disabled={!conversationId}>Nueva conversacion</button></aside><div className="panel chat-panel"><div className="chat-messages">{messages.length?messages.map((message,index)=><article key={message.id??index} className={`chat-message ${message.role}`}><small>{message.role==="user"?data.identity?.username:"Agente"}</small><p>{message.content}</p></article>):<div className="chat-empty"><span className="hub-icon ready">AI</span><h3>Prueba un agente gobernado</h3><p>Selecciona un agente y envía un mensaje. IRIS conservará la sesión y aplicará las tools y policies configuradas.</p></div>}{sending&&<article className="chat-message assistant pending"><small>Agente</small><p>Procesando...</p></article>}</div>{error&&<p className="form-error chat-error">{error}</p>}<form className="chat-composer" onSubmit={submit}><textarea name="message" rows={3} placeholder="Escribe un mensaje..." disabled={sending||!agentName||!data.identity?.authorized}/><button className="primary" disabled={sending||!agentName||!data.identity?.authorized}>{sending?"Enviando...":"Enviar"}</button></form></div></section>
}

function UsersView({users,agents,reload}:{users:AIUser[];agents:Agent[];reload:()=>Promise<void>}){
 const [saving,setSaving]=useState(false),[error,setError]=useState(""),[configure,setConfigure]=useState<AIUser|null>(null);
 async function save(username:string,enabled:boolean){setSaving(true);setError("");try{await api("/ai-users",{method:"POST",body:JSON.stringify({username,enabled})});await reload()}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo actualizar el usuario")}finally{setSaving(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),username=String(f.get("username")||"").trim();if(!username)return;await save(username,true);form.reset()}
 return <><div className="actions"><p>Usuarios IRIS y agentes que pueden ejecutar mediante JWT.</p><form className="user-add" onSubmit={submit}><input name="username" placeholder="Usuario IRIS" required/><button className="primary" disabled={saving}>Dar de alta</button></form></div>{error&&<div className="alert">{error}</div>}<section className="panel table-panel"><table><thead><tr><th>Usuario IRIS</th><th>Agentes permitidos</th><th>Alta</th><th>Acceso</th><th>Gestion</th></tr></thead><tbody>{users.length?users.map(user=><tr key={user.id}><td><strong>{user.username}</strong><small>Alta por {user.createdBy}</small></td><td><Tags values={user.agents}/></td><td>{user.createdAt}</td><td><span className={`status status-${user.enabled?"approved":"suspended"}`}><i/>{user.enabled?"Autorizado":"Bloqueado"}</span></td><td><div className="row-actions"><button className="secondary" onClick={()=>setConfigure(user)}>Agentes</button><button className="secondary" disabled={saving} onClick={()=>void save(user.username,!user.enabled)}>{user.enabled?"Bloquear":"Autorizar"}</button></div></td></tr>):<tr><td colSpan={5} className="empty">No hay usuarios autorizados.</td></tr>}</tbody></table></section>{configure&&<UserAgentsDialog user={configure} agents={agents} close={()=>setConfigure(null)} done={reload}/>}</>
}

function UserAgentsDialog({user,agents,close,done}:{user:AIUser;agents:Agent[];close:()=>void;done:()=>Promise<void>}){const [saving,setSaving]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const values=new FormData(e.currentTarget).getAll("agent");try{await api(`/ai-users/${encodeURIComponent(user.username)}/agents`,{method:"PUT",body:JSON.stringify({agents:values})});await done();close()}catch(reason){setError(reason instanceof Error?reason.message:"No se pudieron asignar los agentes");setSaving(false)}}return <div className="dialog-backdrop" onMouseDown={close}><section className="dialog" onMouseDown={event=>event.stopPropagation()}><button className="dialog-x" onClick={close}>x</button><p className="eyebrow">AUTORIZACION JWT</p><h2>Agentes permitidos</h2><p>Las policies aplicaran estas asignaciones al sujeto <code>{user.username}</code>.</p><form onSubmit={submit}><fieldset className="choice-group"><legend>Agentes</legend>{agents.filter(ok).map(agent=><label key={agent.name}><input type="checkbox" name="agent" value={agent.name} defaultChecked={user.agents.includes(agent.name)}/><span><strong>{agent.displayName}</strong><small>{agent.name}</small></span></label>)}</fieldset>{error&&<p className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Guardando...":"Aplicar"}</button></div></form></section></div>}

type Kind="model"|"tool"|"policy"|"agent";
const copy:Record<Kind,{text:string;button:string;headers:string[]}>= {
 model:{text:"Las credenciales se referencian por Config Store y Secure Wallet.",button:"Registrar modelo",headers:["Modelo","Proveedor","Identificador","Config Store","Estado"]},
 tool:{text:"Metodos publicados por las clases %AI.Tool compiladas en el namespace.",button:"Sincronizar catalogo",headers:["Tool","Implementacion","Autorizacion","Auditoria","Estado","Gestion"]},
 policy:{text:"Las clases se validan contra el contrato AI Hub del tipo elegido.",button:"Registrar policy",headers:["Policy","Tipo","Clase ObjectScript","Estado"]},
 agent:{text:"Las tools se asignan en IRIS y se resuelven al materializar cada agente.",button:"Crear agente",headers:["Agente","Modelo","Tools","Policies","Estado","Gestion"]},
};
function ResourceView({kind,items,data,reload}:{kind:Kind;items:(Model|Tool|Policy|Agent)[];data:Data;reload:()=>Promise<void>}){const [open,setOpen]=useState(false),[configure,setConfigure]=useState<Tool|Agent|null>(null),[working,setWorking]=useState(false),c=copy[kind];async function action(){if(kind!=="tool"){setOpen(true);return}setWorking(true);try{await api("/tools/sync",{method:"POST",body:"{}"});await reload()}finally{setWorking(false)}}return <><div className="actions"><p>{c.text}</p><button className="primary" disabled={working} onClick={()=>void action()}>{kind==="tool"?"":"+ "}{working?"Sincronizando...":c.button}</button></div><section className="panel table-panel"><table><thead><tr>{c.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.length?items.map(item=><Row key={item.id} kind={kind} item={item} configure={()=>setConfigure(item as Tool|Agent)}/>):<tr><td colSpan={c.headers.length} className="empty">Todavia no hay recursos registrados.</td></tr>}</tbody></table></section>{open&&kind!=="tool"&&<ResourceDialog kind={kind} data={data} close={()=>setOpen(false)} done={reload}/>} {configure&&(kind==="tool"||kind==="agent")&&<AssignmentDialog kind={kind} item={configure} data={data} close={()=>setConfigure(null)} done={reload}/>}</>}
function Row({kind,item,configure}:{kind:Kind;item:Model|Tool|Policy|Agent;configure:()=>void}){
 if(kind==="model"){const i=item as Model;return <tr><Name item={i}/><td>{i.provider}</td><td><code>{i.modelId}</code></td><td><code>{i.configName||"-"}</code></td><td><Status item={i}/></td></tr>}
 if(kind==="tool"){const i=item as Tool;return <tr><td><strong>{i.name}</strong><small>{i.description}</small></td><td><code>{i.className}.{i.methodName}()</code></td><td>{i.requiresApproval?"Requerida":"No requerida"}</td><td><Tags values={i.auditPolicies}/></td><td><Status item={i}/></td><td><button className="secondary" onClick={configure}>Policies</button></td></tr>}
 if(kind==="policy"){const i=item as Policy;return <tr><Name item={i}/><td>{labels[i.type]}</td><td><code>{i.className}</code></td><td><Status item={i}/></td></tr>}
 const i=item as Agent;return <tr><Name item={i}/><td><code>{i.modelName}</code><small>T {i.temperature} / {i.maxIterations} iter.</small></td><td><Tags values={i.tools}/></td><td><Tags values={i.policies}/></td><td><Status item={i}/></td><td><button className="secondary" onClick={configure}>Tools</button></td></tr>;
}
function Name({item}:{item:Base}){return <td><strong>{item.displayName}</strong><small>{item.name}</small></td>}
function Status({item}:{item:{status:string;enabled:boolean}}){return <span className={`status status-${item.enabled?item.status:"suspended"}`}><i/>{item.enabled?labels[item.status]??item.status:"Deshabilitado"}</span>}
function Tags({values}:{values:string[]}){return values.length?<div className="tags">{values.map(v=><code key={v}>{v}</code>)}</div>:<span className="muted">Ninguna</span>}

function AssignmentDialog({kind,item,data,close,done}:{kind:"tool"|"agent";item:Tool|Agent;data:Data;close:()=>void;done:()=>Promise<void>}){const [saving,setSaving]=useState(false),[error,setError]=useState("");const isAgent=kind==="agent",current=isAgent?(item as Agent).tools:(item as Tool).auditPolicies,choices=isAgent?data.tools.filter(ok).map(tool=>({value:tool.name,label:tool.name,detail:`${tool.className}.${tool.methodName}()`})):data.policies.filter(policy=>ok(policy)&&policy.type==="audit").map(policy=>({value:policy.name,label:policy.displayName,detail:policy.className}));async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const form=new FormData(e.currentTarget),values=form.getAll("assignment"),path=isAgent?`/agents/${encodeURIComponent(item.name)}/tools`:`/tools/${encodeURIComponent(item.name)}/policies`,payload=isAgent?{tools:values}:{policies:values};try{await api(path,{method:"PUT",body:JSON.stringify(payload)});await done();close()}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo actualizar");setSaving(false)}}return <div className="dialog-backdrop" onMouseDown={close}><section className="dialog" onMouseDown={e=>e.stopPropagation()}><button className="dialog-x" onClick={close}>x</button><p className="eyebrow">GOBIERNO DINAMICO</p><h2>{isAgent?"Tools disponibles para el agente":"Policies de auditoria de la tool"}</h2><p><code>{item.name}</code></p><form onSubmit={submit}><fieldset className="choice-group"><legend>{isAgent?"Tools permitidas":"Auditorias aplicables"}</legend>{choices.length?choices.map(choice=><label key={choice.value}><input type="checkbox" name="assignment" value={choice.value} defaultChecked={current.includes(choice.value)}/><span><strong>{choice.label}</strong><small>{choice.detail}</small></span></label>):<p>No hay recursos aprobados.</p>}</fieldset>{error&&<p className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Guardando...":"Aplicar"}</button></div></form></section></div>}

type FormKind=Exclude<Kind,"tool">;
const dialogCopy:Record<FormKind,{title:string;subtitle:string;path:string}>={model:{title:"Registrar modelo",subtitle:"Alta gobernada; no introduzcas secretos aqui.",path:"/models"},policy:{title:"Registrar policy",subtitle:"Se valida la herencia segun su tipo.",path:"/policies"},agent:{title:"Crear agente",subtitle:"Selecciona el modelo, los metodos %AI.Tool y las policies.",path:"/agents"}};
function ResourceDialog({kind,data,close,done}:{kind:FormKind;data:Data;close:()=>void;done:()=>Promise<void>}){const [saving,setSaving]=useState(false),[error,setError]=useState(""),c=dialogCopy[kind];async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget),raw=Object.fromEntries(f),payload=kind==="agent"?{...raw,temperature:Number(raw.temperature),maxIterations:Number(raw.maxIterations),tools:f.getAll("tools"),policies:f.getAll("policies")}:raw;try{await api(c.path,{method:"POST",body:JSON.stringify(payload)});await done();close()}catch(reason){setError(reason instanceof Error?reason.message:"No se pudo registrar");setSaving(false)}}return <div className="dialog-backdrop" onMouseDown={close}><section className="dialog" onMouseDown={e=>e.stopPropagation()}><button className="dialog-x" onClick={close}>x</button><p className="eyebrow">NUEVO RECURSO</p><h2>{c.title}</h2><p>{c.subtitle}</p><form onSubmit={submit}><Fields kind={kind} data={data}/>{error&&<p className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Registrando...":"Registrar"}</button></div></form></section></div>}
function Fields({kind,data}:{kind:FormKind;data:Data}){if(kind==="model")return <Grid><Field label="Nombre logico"><input name="name" required/></Field><Field label="Nombre visible"><input name="displayName" required/></Field><Field label="Proveedor"><select name="provider">{data.providers.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><Field label="Model ID"><input name="modelId" required/></Field><Field label="Configuracion AI Hub"><input name="configName" placeholder="AI.LLM.OpenAI.Production"/></Field><Lifecycle/></Grid>;
 if(kind==="policy")return <Grid><Field label="Nombre logico"><input name="name" required/></Field><Field label="Nombre visible"><input name="displayName" required/></Field><Field label="Tipo"><select name="type"><option value="authorization">Autorizacion</option><option value="audit">Auditoria</option><option value="discovery">Descubrimiento</option></select></Field><Field label="Clase ObjectScript"><input name="className" required/></Field><Field label="Descripcion" wide><input name="description"/></Field><Lifecycle/></Grid>;
 const models=data.models.filter(ok),tools=data.tools.filter(ok),policies=data.policies.filter(ok);return <Grid><Field label="Nombre logico"><input name="name" required/></Field><Field label="Nombre visible"><input name="displayName" required/></Field><Field label="Modelo"><select name="modelName" required><option value="">Selecciona...</option>{models.map(m=><option value={m.name} key={m.id}>{m.displayName}</option>)}</select></Field><Field label="Temperatura"><input name="temperature" type="number" min="0" max="2" step="0.05" defaultValue="0.2"/></Field><Field label="Max. iteraciones"><input name="maxIterations" type="number" min="1" max="100" defaultValue="10"/></Field><Lifecycle/><Field label="System prompt" wide><textarea name="systemPrompt" rows={4}/></Field><Choices title="Tools permitidas" name="tools" items={tools.map(i=>({value:i.name,label:i.name,detail:`${i.className}.${i.methodName}()`}))}/><Choices title="Policies globales" name="policies" items={policies.map(i=>({value:i.name,label:i.displayName,detail:labels[i.type]}))}/></Grid>}
const ok=(i:{status:string;enabled:boolean})=>i.status==="approved"&&i.enabled;
function Grid({children}:{children:React.ReactNode}){return <div className="form-grid">{children}</div>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"field wide":"field"}><span>{label}</span>{children}</label>}
function Lifecycle(){return <Field label="Estado"><select name="status"><option value="draft">Borrador</option><option value="approved">Aprobado</option></select></Field>}
function Choices({title,name,items}:{title:string;name:string;items:{value:string;label:string;detail:string}[]}){return <fieldset className="choice-group"><legend>{title}</legend>{items.length?items.map(i=><label key={i.value}><input type="checkbox" name={name} value={i.value}/><span><strong>{i.label}</strong><small>{i.detail}</small></span></label>):<p>No hay recursos aprobados.</p>}</fieldset>}
