import { FormEvent, useCallback, useEffect, useState } from "react";
import { LanguageSwitcher, translateCurrent, useI18n } from "./i18n";

type Tab = "overview" | "chat" | "models" | "tools" | "policies" | "agents" | "users" | "audit";
type Base = { id:number; name:string; displayName:string; description?:string; status:string; enabled:boolean; createdAt:string };
type Health = { status:string; service:string; platform:string };
type Provider = { id:string; name:string; experimental:boolean; fields:string[] };
type Model = Base & { provider:string; modelId:string; apiKey:string; baseUrl:string; orgId:string; version:string; region:string; bearerToken:string; projectId:string; serviceAccountPath:string; siteUrl:string; siteName:string };
type Tool = Omit<Base,"displayName"> & { className:string; methodName:string; description:string; requiresApproval:boolean; schema:string; auditPolicies:string[] };
type Policy = Base & { className:string; type:"authorization"|"audit"|"discovery" };
type Agent = Base & { modelName:string; systemPrompt:string; temperature:number; maxIterations:number; tools:string[]; policies:string[] };
type AuditEvent = { id:number; requestId:string; agentName:string; toolName:string; policyName:string; arguments:string; resultPreview:string; success:boolean; durationMs:number; error:string; createdAt:string };
type Identity = { username:string; authorized:boolean };
type JWTSession = { access_token:string; refresh_token:string; sub:string; iat:number; exp:number };
type AIUser = { id:number; username:string; enabled:boolean; createdAt:string; createdBy:string; agents:string[] };
type ChatMessage = { id?:number; requestId?:string; role:"user"|"assistant"; content:string; createdAt?:string };
type ChatResponse = { requestId:string; conversationId:string; agentName:string; username:string; content:string; messages:ChatMessage[] };
type Data = { health:Health|null; identity:Identity|null; providers:Provider[]; models:Model[]; tools:Tool[]; policies:Policy[]; agents:Agent[]; availableAgents:Agent[]; users:AIUser[]; audits:AuditEvent[] };

const empty:Data={health:null,identity:null,providers:[],models:[],tools:[],policies:[],agents:[],availableAgents:[],users:[],audits:[]};
const titleKeys:Record<Tab,string>={overview:"nav.overview",chat:"nav.chat",models:"nav.models",tools:"nav.tools",policies:"nav.policies",agents:"nav.agents",users:"nav.users",audit:"nav.audit"};
const jwtStorageKey="irisJWT";
const readJWT=():JWTSession|null=>{try{return JSON.parse(sessionStorage.getItem(jwtStorageKey)||"null") as JWTSession|null}catch{return null}};
const saveJWT=(tokens:JWTSession)=>sessionStorage.setItem(jwtStorageKey,JSON.stringify(tokens));
let refreshInFlight:Promise<JWTSession>|null=null;
async function tokenRequest(path:"/login"|"/refresh",body:object):Promise<JWTSession>{const response=await fetch(`/api/app${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json().catch(()=>({})) as Partial<JWTSession>&{error?:string};if(!response.ok||!result.access_token)throw new Error(result.error??translateCurrent("error.token"));return result as JWTSession}
async function refreshJWT():Promise<JWTSession>{const current=readJWT();if(!current?.refresh_token)throw new Error(translateCurrent("error.expired"));if(!refreshInFlight)refreshInFlight=tokenRequest("/refresh",{refresh_token:current.refresh_token,grant_type:"refresh_token"}).then(tokens=>{if(!tokens.sub)tokens.sub=current.sub;saveJWT(tokens);return tokens}).finally(()=>{refreshInFlight=null});return refreshInFlight}
async function api<T>(path:string,options?:RequestInit,retried=false):Promise<T>{const tokens=readJWT();if(!tokens)throw new Error(translateCurrent("error.noSession"));const response=await fetch(`/api/app${path}`,{...options,headers:{"Content-Type":"application/json; charset=UTF-8",Authorization:`Bearer ${tokens.access_token}`,...options?.headers}});if(response.status===401&&!retried){await refreshJWT();return api<T>(path,options,true)}let body:unknown={};try{body=await response.json()}catch{body={}}if(!response.ok)throw new Error((body as {error?:string}).error??`HTTP ${response.status}`);return body as T;}

export function App(){
 const {t}=useI18n();
 const [tab,setTab]=useState<Tab>("overview"),[data,setData]=useState<Data>(empty),[error,setError]=useState(""),[authenticated,setAuthenticated]=useState(()=>Boolean(readJWT()));
 const reload=useCallback(async()=>{try{setError("");const [health,providers,models,tools,policies,agents,availableAgents,users,audits]=await Promise.all([api<Health>("/health"),api<Provider[]>("/providers"),api<Model[]>("/models"),api<Tool[]>("/tools"),api<Policy[]>("/policies"),api<Agent[]>("/agents"),api<Agent[]>("/my-agents"),api<AIUser[]>("/ai-users"),api<AuditEvent[]>("/audit-events")]);const username=readJWT()?.sub??"";setData({health,identity:{username,authorized:availableAgents.length>0},providers,models,tools,policies,agents,availableAgents,users,audits});}catch(e){setError(e instanceof Error?e.message:t("error.load"));}},[t]);
 useEffect(()=>{if(authenticated)void reload();},[authenticated,reload]);
 useEffect(()=>{document.title=`${t(titleKeys[tab])} · Governance Hub`;},[tab,t]);
 if(!authenticated)return <LoginView authenticated={()=>setAuthenticated(true)}/>;
 async function logout(){const tokens=readJWT();try{if(tokens)await fetch("/api/app/logout",{method:"POST",headers:{Authorization:`Bearer ${tokens.access_token}`}})}finally{sessionStorage.removeItem(jwtStorageKey);setData(empty);setAuthenticated(false)}}
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">AI</span><div><strong>Governance Hub</strong><small>InterSystems AI Hub</small></div></div><nav>{(["overview","chat","models","tools","policies","agents","users","audit"] as Tab[]).map((item,index)=><button key={item} className={tab===item?"nav-item active":"nav-item"} onClick={()=>setTab(item)}><span>{(index+1).toString().padStart(2,"0")}</span>{t(titleKeys[item])}</button>)}</nav><div className="sidebar-foot"><span className={`pulse ${data.health?"online":""}`}/><div><strong>{data.identity?.username||"AI Hub"}</strong><small>{data.identity?.authorized?t("common.authorizedUser"):data.health?t("common.noAgentAccess"):t("common.connecting")}</small></div></div></aside><main className="content"><header className="topbar"><div><p className="eyebrow">{t("common.controlPlane")}</p><h1>{t(titleKeys[tab])}</h1></div><div className="topbar-actions"><LanguageSwitcher compact/><div className="environment"><span>{t("common.irisUser")}</span><strong>{data.identity?.username||"-"}</strong><button className="secondary" onClick={logout}>{t("common.logout")}</button></div></div></header>{error&&<div className="alert">{error}<button onClick={()=>void reload()}>{t("common.retry")}</button></div>}<View tab={tab} data={data} reload={reload}/></main></div>;
}

function LoginView({authenticated}:{authenticated:()=>void}){const {t}=useI18n();const [error,setError]=useState(""),[loading,setLoading]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const form=new FormData(e.currentTarget),user=String(form.get("username")||""),password=String(form.get("password")||"");try{const tokens=await tokenRequest("/login",{user,password});saveJWT(tokens);authenticated()}catch(reason){sessionStorage.removeItem(jwtStorageKey);setError(reason instanceof Error?reason.message:t("error.login"));setLoading(false)}}return <main className="login-shell"><div className="login-language"><LanguageSwitcher/></div><section className="panel login-card"><span className="brand-mark">AI</span><p className="eyebrow">{t("login.eyebrow")}</p><h1>Governance Hub</h1><p>{t("login.description")}</p><form onSubmit={submit}><label className="field"><span>{t("login.username")}</span><input name="username" autoComplete="username" required/></label><label className="field"><span>{t("login.password")}</span><input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p className="form-error">{error}</p>}<button className="primary" disabled={loading}>{loading?t("login.loading"):t("login.submit")}</button></form></section></main>}

function View({tab,data,reload}:{tab:Tab;data:Data;reload:()=>Promise<void>}){
 if(tab==="overview")return <Overview data={data}/>;
 if(tab==="chat")return <ChatView data={data}/>;
 if(tab==="users")return <UsersView users={data.users} agents={data.agents} reload={reload}/>;
 if(tab==="audit")return <AuditView events={data.audits}/>;
 if(tab==="models")return <ResourceView kind="model" items={data.models} data={data} reload={reload}/>;
 if(tab==="tools")return <ResourceView kind="tool" items={data.tools} data={data} reload={reload}/>;
 if(tab==="policies")return <ResourceView kind="policy" items={data.policies} data={data} reload={reload}/>;
 return <ResourceView kind="agent" items={data.agents} data={data} reload={reload}/>;
}
function Overview({data}:{data:Data}){const {t}=useI18n();const approved=(items:{status:string;enabled:boolean}[])=>items.filter(i=>i.status==="approved"&&i.enabled).length;return <><section className="hero-panel"><div><p className="eyebrow">{t("overview.eyebrow")}</p><h2>{t("overview.title")}</h2><p>{t("overview.description")}</p></div><div className="hub-state"><span className="hub-icon ready">AI</span><strong>{t("overview.hubActive")}</strong><small>{t("overview.nativeGovernance")}</small></div></section><section className="metrics four"><Metric value={approved(data.models)} label={t("overview.activeModels")}/><Metric value={approved(data.tools)} label={t("overview.publishableTools")}/><Metric value={approved(data.policies)} label={t("overview.activePolicies")}/><Metric value={approved(data.agents)} label={t("overview.activeAgents")}/></section><section className="panel architecture"><div className="section-title"><p className="eyebrow">{t("overview.flow")}</p><h3>{t("overview.fromMethod")}</h3></div><div className="flow"><Flow n="01" title={t("overview.define")} text="%AI.Tool"/><b>-</b><Flow n="02" title={t("overview.discover")} text={t("overview.namespaceCatalog")}/><b>-</b><Flow n="03" title={t("overview.assign")} text={t("overview.toolsPolicies")}/><b>-</b><Flow n="04" title={t("overview.execute")} text="%AI.Agent"/></div></section></>}
function Metric({value,label}:{value:number;label:string}){const {t}=useI18n();return <article className="metric"><strong>{value.toString().padStart(2,"0")}</strong><span>{label}</span><small>{t("overview.approvedEnabled")}</small></article>}
function Flow({n,title,text}:{n:string;title:string;text:string}){return <div className="flow-step"><small>{n}</small><strong>{title}</strong><span>{text}</span></div>}
function AuditView({events}:{events:AuditEvent[]}){const {t}=useI18n();return <section className="panel table-panel"><table><thead><tr>{["date","request","agent","tool","policy","duration","result"].map(key=><th key={key}>{t(`audit.${key}`)}</th>)}</tr></thead><tbody>{events.length?events.map(event=><tr key={event.id}><td>{event.createdAt}</td><td><code>{event.requestId||"-"}</code></td><td><code>{event.agentName}</code></td><td><code>{event.toolName}</code></td><td><code>{event.policyName}</code></td><td>{event.durationMs} ms</td><td><span className={`status status-${event.success?"approved":"suspended"}`}><i/>{event.success?t("audit.success"):t("audit.error")}</span><small>{event.error||event.resultPreview}</small></td></tr>):<tr><td colSpan={7} className="empty">{t("audit.empty")}</td></tr>}</tbody></table></section>}

function ChatView({data}:{data:Data}){
 const {t}=useI18n();
 const available=data.availableAgents.filter(ok),[agentName,setAgentName]=useState(""),[conversationId,setConversationId]=useState(""),[messages,setMessages]=useState<ChatMessage[]>([]),[sending,setSending]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!agentName&&available.length)setAgentName(available[0].name)},[agentName,available]);
 function changeAgent(value:string){setAgentName(value);setConversationId("");setMessages([]);setError("")}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,field=form.elements.namedItem("message") as HTMLTextAreaElement,message=field.value.trim();if(!message||!agentName)return;setSending(true);setError("");setMessages(previous=>[...previous,{role:"user",content:message}]);field.value="";try{const response=await api<ChatResponse>("/chat",{method:"POST",body:JSON.stringify({agentName,message,conversationId})});setConversationId(response.conversationId);setMessages(response.messages)}catch(reason){setMessages(previous=>previous.slice(0,-1));setError(reason instanceof Error?reason.message:t("error.chat"))}finally{setSending(false)}}
 return <section className="chat-layout"><aside className="panel chat-config"><p className="eyebrow">{t("chat.context")}</p><label className="field"><span>{t("chat.agent")}</span><select value={agentName} onChange={e=>changeAgent(e.target.value)}><option value="">{t("common.select")}</option>{available.map(agent=><option key={agent.id} value={agent.name}>{agent.displayName}</option>)}</select></label><div className="chat-identity"><span>{t("common.irisUser")}</span><strong>{data.identity?.username||"-"}</strong><small className={data.identity?.authorized?"allowed":"denied"}>{data.identity?.authorized?t("chat.authorized"):t("chat.denied")}</small></div>{conversationId&&<div className="chat-session"><span>{t("chat.conversation")}</span><code>{conversationId}</code></div>}<button className="secondary" onClick={()=>changeAgent(agentName)} disabled={!conversationId}>{t("chat.newConversation")}</button></aside><div className="panel chat-panel"><div className="chat-messages">{messages.length?messages.map((message,index)=><article key={message.id??index} className={`chat-message ${message.role}`}><small>{message.role==="user"?data.identity?.username:t("chat.agent")}</small><p>{message.content}</p></article>):<div className="chat-empty"><span className="hub-icon ready">AI</span><h3>{t("chat.testTitle")}</h3><p>{t("chat.testDescription")}</p></div>}{sending&&<article className="chat-message assistant pending"><small>{t("chat.agent")}</small><p>{t("chat.processing")}</p></article>}</div>{error&&<p className="form-error chat-error">{error}</p>}<form className="chat-composer" onSubmit={submit}><textarea name="message" rows={3} placeholder={t("chat.placeholder")} disabled={sending||!agentName||!data.identity?.authorized}/><button className="primary" disabled={sending||!agentName||!data.identity?.authorized}>{sending?t("chat.sending"):t("chat.send")}</button></form></div></section>
}

function UsersView({users,agents,reload}:{users:AIUser[];agents:Agent[];reload:()=>Promise<void>}){
 const {t}=useI18n();
 const [saving,setSaving]=useState(false),[error,setError]=useState(""),[configure,setConfigure]=useState<AIUser|null>(null);
 async function save(username:string,enabled:boolean){setSaving(true);setError("");try{await api("/ai-users",{method:"POST",body:JSON.stringify({username,enabled})});await reload()}catch(reason){setError(reason instanceof Error?reason.message:t("error.user"))}finally{setSaving(false)}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),username=String(f.get("username")||"").trim();if(!username)return;await save(username,true);form.reset()}
 return <><div className="actions"><p>{t("users.description")}</p><form className="user-add" onSubmit={submit}><input name="username" placeholder={t("common.irisUser")} required/><button className="primary" disabled={saving}>{t("users.add")}</button></form></div>{error&&<div className="alert">{error}</div>}<section className="panel table-panel"><table><thead><tr>{[t("common.irisUser"),t("users.allowedAgents"),t("users.registered"),t("users.access"),t("users.management")].map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{users.length?users.map(user=><tr key={user.id}><td><strong>{user.username}</strong><small>{t("users.createdBy",{user:user.createdBy})}</small></td><td><Tags values={user.agents}/></td><td>{user.createdAt}</td><td><span className={`status status-${user.enabled?"approved":"suspended"}`}><i/>{user.enabled?t("users.authorized"):t("users.blocked")}</span></td><td><div className="row-actions"><button className="secondary" onClick={()=>setConfigure(user)}>{t("users.agents")}</button><button className="secondary" disabled={saving} onClick={()=>void save(user.username,!user.enabled)}>{user.enabled?t("users.block"):t("users.authorize")}</button></div></td></tr>):<tr><td colSpan={5} className="empty">{t("users.empty")}</td></tr>}</tbody></table></section>{configure&&<UserAgentsDialog user={configure} agents={agents} close={()=>setConfigure(null)} done={reload}/>}</>
}

function UserAgentsDialog({user,agents,close,done}:{user:AIUser;agents:Agent[];close:()=>void;done:()=>Promise<void>}){const {t}=useI18n();const [saving,setSaving]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const values=new FormData(e.currentTarget).getAll("agent");try{await api(`/ai-users/${encodeURIComponent(user.username)}/agents`,{method:"PUT",body:JSON.stringify({agents:values})});await done();close()}catch(reason){setError(reason instanceof Error?reason.message:t("error.userAgents"));setSaving(false)}}return <div className="dialog-backdrop" onMouseDown={close}><section className="dialog" onMouseDown={event=>event.stopPropagation()}><button className="dialog-x" onClick={close} aria-label={t("common.cancel")}>×</button><p className="eyebrow">{t("users.jwtAuthorization")}</p><h2>{t("users.allowedAgents")}</h2><p>{t("users.assignmentDescription",{user:user.username})}</p><form onSubmit={submit}><fieldset className="choice-group"><legend>{t("users.agents")}</legend>{agents.filter(ok).map(agent=><label key={agent.name}><input type="checkbox" name="agent" value={agent.name} defaultChecked={user.agents.includes(agent.name)}/><span><strong>{agent.displayName}</strong><small>{agent.name}</small></span></label>)}</fieldset>{error&&<p className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={close}>{t("common.cancel")}</button><button className="primary" disabled={saving}>{saving?t("common.applying"):t("common.apply")}</button></div></form></section></div>}

type Kind="model"|"tool"|"policy"|"agent";
const resourceKeys:Record<Kind,string>={model:"models",tool:"tools",policy:"policies",agent:"agents"};
function ResourceView({kind,items,data,reload}:{kind:Kind;items:(Model|Tool|Policy|Agent)[];data:Data;reload:()=>Promise<void>}){const {t}=useI18n();const [creating,setCreating]=useState(false),[editing,setEditing]=useState<Model|Tool|Agent|null>(null),[working,setWorking]=useState(false),base=`resource.${resourceKeys[kind]}`,headers=t(`${base}.headers`).split("|");async function action(){if(kind!=="tool"){setCreating(true);return}setWorking(true);try{await api("/tools/sync",{method:"POST",body:"{}"});await reload()}finally{setWorking(false)}}return <><div className="actions"><p>{t(`${base}.description`)}</p><button className="primary" disabled={working} onClick={()=>void action()}>{kind==="tool"?"":"+ "}{working?t("resource.syncing"):t(`${base}.action`)}</button></div><section className="panel table-panel"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{items.length?items.map(item=><Row key={item.id} kind={kind} item={item} edit={kind==="policy"?undefined:()=>setEditing(item as Model|Tool|Agent)}/>):<tr><td colSpan={headers.length} className="empty">{t("resource.empty")}</td></tr>}</tbody></table></section>{creating&&kind!=="tool"&&<ResourceDialog kind={kind} data={data} close={()=>setCreating(false)} done={reload}/>} {editing&&<ResourceDialog kind={kind as "model"|"tool"|"agent"} item={editing} data={data} close={()=>setEditing(null)} done={reload}/>}</>}
function Row({kind,item,edit}:{kind:Kind;item:Model|Tool|Policy|Agent;edit?:()=>void}){
 const {t}=useI18n();
 if(kind==="model"){const i=item as Model;return <tr><Name item={i}/><td>{i.provider}</td><td><code>{i.modelId}</code></td><td><code>{modelConfiguredFields(i).join(", ")||"-"}</code></td><td><Status item={i}/></td><td><button className="secondary" onClick={edit}>{t("common.edit")}</button></td></tr>}
 if(kind==="tool"){const i=item as Tool;return <tr><td><strong>{i.name}</strong><small>{i.description}</small></td><td><code>{i.className}.{i.methodName}()</code></td><td>{i.requiresApproval?t("resource.required"):t("resource.notRequired")}</td><td><Tags values={i.auditPolicies}/></td><td><Status item={i}/></td><td><button className="secondary" onClick={edit}>{t("common.edit")}</button></td></tr>}
 if(kind==="policy"){const i=item as Policy;return <tr><Name item={i}/><td>{t(`type.${i.type}`)}</td><td><code>{i.className}</code></td><td><Status item={i}/></td></tr>}
 const i=item as Agent;return <tr><Name item={i}/><td><code>{i.modelName}</code><small>T {i.temperature} / {i.maxIterations} {t("resource.iterations")}</small></td><td><Tags values={i.tools}/></td><td><Tags values={i.policies}/></td><td><Status item={i}/></td><td><button className="secondary" onClick={edit}>{t("common.edit")}</button></td></tr>;
}
function Name({item}:{item:Base}){return <td><strong>{item.displayName}</strong><small>{item.name}</small></td>}
function Status({item}:{item:{status:string;enabled:boolean}}){const {t}=useI18n();return <span className={`status status-${item.enabled?item.status:"suspended"}`}><i/>{item.enabled?t(`status.${item.status}`):t("status.disabled")}</span>}
function Tags({values}:{values:string[]}){const {t}=useI18n();return values.length?<div className="tags">{values.map(v=><code key={v}>{v}</code>)}</div>:<span className="muted">{t("common.none")}</span>}

type FormKind=Kind;
const dialogPaths:Record<FormKind,string>={model:"/models",tool:"/tools",policy:"/policies",agent:"/agents"};
function ResourceDialog({kind,item,data,close,done}:{kind:FormKind;item?:Model|Tool|Policy|Agent;data:Data;close:()=>void;done:()=>Promise<void>}){const {t}=useI18n();const [saving,setSaving]=useState(false),[error,setError]=useState(""),editing=Boolean(item),pathBase=dialogPaths[kind];async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget),raw=Object.fromEntries(f);let payload:Record<string,unknown>={...raw,enabled:f.has("enabled")};if(kind==="agent")payload={...payload,temperature:Number(raw.temperature),maxIterations:Number(raw.maxIterations),tools:f.getAll("tools"),policies:f.getAll("policies")};if(kind==="tool")payload={...payload,requiresApproval:f.has("requiresApproval"),auditPolicies:f.getAll("auditPolicies")};const path=editing?`${pathBase}/${encodeURIComponent(item!.name)}`:pathBase;try{await api(path,{method:editing?"PUT":"POST",body:JSON.stringify(payload)});await done();close()}catch(reason){setError(reason instanceof Error?reason.message:t("error.save"));setSaving(false)}}return <div className="dialog-backdrop" onMouseDown={close}><section className="dialog resource-dialog" onMouseDown={e=>e.stopPropagation()}><button className="dialog-x" onClick={close} aria-label={t("common.cancel")}>×</button><p className="eyebrow">{t(editing?"dialog.detail":"dialog.new")}</p><h2>{t(`dialog.${kind}.${editing?"edit":"create"}`)}</h2><p>{t(`dialog.${kind}.subtitle`)}</p><form onSubmit={submit}><Fields kind={kind} item={item} data={data}/>{error&&<p className="form-error">{error}</p>}<div className="dialog-actions"><button type="button" className="secondary" onClick={close}>{t("common.cancel")}</button><button className="primary" disabled={saving}>{saving?t("common.applying"):editing?t("common.saveChanges"):t("common.register")}</button></div></form></section></div>}
function Fields({kind,item,data}:{kind:FormKind;item?:Model|Tool|Policy|Agent;data:Data}){const {t}=useI18n();const editing=Boolean(item);if(kind==="model")return <ModelFields model={item as Model|undefined} data={data} editing={editing}/>;
 if(kind==="tool"){const tool=item as Tool;const audits=data.policies.filter(policy=>policy.type==="audit"&&(ok(policy)||tool.auditPolicies.includes(policy.name)));return <Grid><Metadata item={tool}/><Field label={t("field.logicalName")}><input name="name" required readOnly defaultValue={tool.name}/></Field><Field label={t("field.objectScriptClass")}><input name="className" readOnly defaultValue={tool.className}/></Field><Field label={t("field.method")}><input name="methodName" readOnly defaultValue={tool.methodName}/></Field><Field label={t("field.description")} wide><textarea name="description" rows={3} defaultValue={tool.description}/></Field><label className="checkbox"><input name="requiresApproval" type="checkbox" defaultChecked={tool.requiresApproval}/> {t("field.requiresApproval")}</label><Lifecycle status={tool.status} enabled={tool.enabled}/><Field label={t("field.discoveredDescriptor")} wide><textarea name="schema" rows={8} readOnly defaultValue={formatJSON(tool.schema)}/></Field><Choices title={t("field.auditPolicies")} name="auditPolicies" items={audits.map(i=>({value:i.name,label:i.displayName,detail:i.className}))} selected={tool.auditPolicies}/></Grid>}
 if(kind==="policy"){const policy=item as Policy|undefined;return <Grid><Metadata item={policy}/><Field label={t("field.logicalName")}><input name="name" required readOnly={editing} defaultValue={policy?.name}/></Field><Field label={t("field.displayName")}><input name="displayName" required defaultValue={policy?.displayName}/></Field><Field label={t("field.type")}><select name="type" defaultValue={policy?.type}>{["authorization","audit","discovery"].map(type=><option key={type} value={type}>{t(`type.${type}`)}</option>)}</select></Field><Field label={t("field.objectScriptClass")}><input name="className" required defaultValue={policy?.className}/></Field><Field label={t("field.description")} wide><input name="description" defaultValue={policy?.description}/></Field><Lifecycle status={policy?.status} enabled={policy?.enabled}/></Grid>}
 const agent=item as Agent|undefined,models=data.models,tools=data.tools,policies=data.policies;return <Grid><Metadata item={agent}/><Field label={t("field.logicalName")}><input name="name" required readOnly={editing} defaultValue={agent?.name}/></Field><Field label={t("field.displayName")}><input name="displayName" required defaultValue={agent?.displayName}/></Field><Field label={t("field.model")}><select name="modelName" required defaultValue={agent?.modelName||""}><option value="">{t("common.select")}</option>{models.map(m=><option value={m.name} key={m.id}>{m.displayName} · {t(`status.${m.status}`)}</option>)}</select></Field><Field label={t("field.temperature")}><input name="temperature" type="number" min="0" max="2" step="0.05" defaultValue={agent?.temperature??0.2}/></Field><Field label={t("field.maxIterations")}><input name="maxIterations" type="number" min="1" max="100" defaultValue={agent?.maxIterations??10}/></Field><Lifecycle status={agent?.status} enabled={agent?.enabled}/><Field label={t("field.systemPrompt")} wide><textarea name="systemPrompt" rows={5} defaultValue={agent?.systemPrompt}/></Field><Choices title={t("field.allowedTools")} name="tools" items={tools.map(i=>({value:i.name,label:i.name,detail:`${i.className}.${i.methodName}()`}))} selected={agent?.tools}/><Choices title={t("field.globalPolicies")} name="policies" items={policies.map(i=>({value:i.name,label:i.displayName,detail:t(`type.${i.type}`)}))} selected={agent?.policies}/></Grid>}
const modelFieldMeta:Record<string,{name:string;labelKey?:string;label?:string;placeholder?:string}>={api_key:{name:"apiKey",label:"API key",placeholder:"secret://secret-name"},base_url:{name:"baseUrl",label:"Base URL",placeholder:"https://..."},org_id:{name:"orgId",label:"Organization ID"},version:{name:"version",labelKey:"field.apiVersion"},region:{name:"region",labelKey:"field.region"},bearer_token:{name:"bearerToken",label:"Bearer token",placeholder:"secret://secret-name"},project_id:{name:"projectId",label:"Project ID"},service_account_path:{name:"serviceAccountPath",labelKey:"field.serviceAccountPath"},site_url:{name:"siteUrl",labelKey:"field.siteUrl"},site_name:{name:"siteName",labelKey:"field.siteName"}};
function ModelFields({model,data,editing}:{model?:Model;data:Data;editing:boolean}){const {t}=useI18n();const [provider,setProvider]=useState(model?.provider??data.providers[0]?.id??""),definition=data.providers.find(item=>item.id===provider),fields=definition?.fields??[];return <Grid><Metadata item={model}/><Field label={t("field.logicalName")}><input name="name" required readOnly={editing} defaultValue={model?.name}/></Field><Field label={t("field.displayName")}><input name="displayName" required defaultValue={model?.displayName}/></Field><Field label={t("field.provider")}><select name="provider" value={provider} onChange={event=>setProvider(event.target.value)}>{data.providers.map(item=><option value={item.id} key={item.id}>{item.name}{item.experimental?` · ${t("common.experimental")}`:""}</option>)}</select></Field><Field label={t("field.modelId")}><input name="modelId" required defaultValue={model?.modelId}/></Field>{fields.map(field=>{const meta=modelFieldMeta[field]??{name:field,label:field},value=model?String((model as unknown as Record<string,unknown>)[meta.name]??""):"";return <Field label={meta.labelKey?t(meta.labelKey):meta.label??field} key={`${provider}-${field}`}><input name={meta.name} defaultValue={value} placeholder={meta.placeholder} autoComplete="off"/></Field>})}<Lifecycle status={model?.status} enabled={model?.enabled}/></Grid>}
function modelConfiguredFields(model:Model){return Object.entries(modelFieldMeta).filter(([,meta])=>Boolean((model as unknown as Record<string,unknown>)[meta.name])).map(([field])=>field)}
const ok=(i:{status:string;enabled:boolean})=>i.status==="approved"&&i.enabled;
function Grid({children}:{children:React.ReactNode}){return <div className="form-grid">{children}</div>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"field wide":"field"}><span>{label}</span>{children}</label>}
function Metadata({item}:{item?:{id:number;createdAt:string}}){const {t}=useI18n();return item?<div className="resource-meta"><span>ID <strong>{item.id}</strong></span><span>{t("common.created")} <strong>{item.createdAt||"-"}</strong></span></div>:null}
function Lifecycle({status="draft",enabled=true}:{status?:string;enabled?:boolean}){const {t}=useI18n();return <><Field label={t("field.status")}><select name="status" defaultValue={status}>{["draft","approved","suspended","retired"].map(value=><option value={value} key={value}>{t(`status.${value}`)}</option>)}</select></Field><label className="checkbox"><input name="enabled" type="checkbox" defaultChecked={enabled}/> {t("common.enabled")}</label></>}
function Choices({title,name,items,selected=[]}:{title:string;name:string;items:{value:string;label:string;detail:string}[];selected?:string[]}){const {t}=useI18n();return <fieldset className="choice-group"><legend>{title}</legend>{items.length?items.map(i=><label key={i.value}><input type="checkbox" name={name} value={i.value} defaultChecked={selected.includes(i.value)}/><span><strong>{i.label}</strong><small>{i.detail}</small></span></label>):<p>{t("common.noResources")}</p>}</fieldset>}
function formatJSON(value:string){try{return JSON.stringify(JSON.parse(value),null,2)}catch{return value}}
